<template>
  <div class="upload-form">
    <div class="front-screen slidepad">
      <div class="container-fluid">
        <h1 class="front-screen-title">Upload</h1>
      </div>
    </div>
    <div class="slidepad content-box" style="position: relative">
      <div class="container-fluid">
        <div style="position: relative">
          <h2>File
            <i class="fa fa-question-circle-o" @click="showInfo = !showInfo"></i>
          </h2>
          <div class="info" v-if="showInfo">
            <div
              style="position: fixed;top: 0;bottom: 0;left: 0;right: 0;background: rgba(255,255,255,0)"
              @click="showInfo = false"
            ></div>
            <p>The input data should be a static image in any format.
              <br>It will be uploaded to the encoding server and processed into the shape which matches the model input.
            </p>
            <p>The model data should be a fixed-point model. It requires a directory "data", and two files in the "data" directory which are "symbol" file and "params" file. More specifically, the directory structure is as follows:
              <br>...data
              <br>...data/symbol
              <br>...data/params
            </p>
            <p
              style="margin-bottom: 0"
            >After submitting the model files, accept the torrent file generated by this system and seed it with any third-party bt client. Secondly, confirm the transaction to submit the metainfo of this model to the blockchain. Finally, complete the upload by pushing the progress.</p>
          </div>
        </div>



        <form id="TypeRadios" style="outline: none">
            <div class="row">
                <div class="col-sm-4">
                    <label class="btn-upload">
                    <input type="radio" v-model="selectedType" name="radioSubComponent" value="input_data"/>&nbsp;&nbsp; Input Data
                    </label>
                </div>
                <div class="col-sm-4">
                    <label class="btn-upload">
                    <input type="radio" v-model="selectedType" name="radioSubComponent" value="model_data"/>&nbsp;&nbsp; Fixed Point Model Data
                    </label>
                </div>
                <div class="col-sm-4">
                    <label class="btn-upload">
                    <input type="radio" v-model="selectedType" name="radioSubComponent" value="float_model_data"/>&nbsp;&nbsp; Float Point Model Data
                    <div class="upload-info">If your model is not determistic, we can provide the processing service. You only need to pay a certain fee and leave your email address in description. We will send you the determistic model.</div>
                    </label>
                </div>
            </div>
        </form>

        <b-form v-if="show">
          <b-form-group>
            <b-row>
              <b-col sm="6">
                <b-row>
                  <b-col sm="6" style="margin-bottom: 30px">
                    <b-button
                      @click="$refs.fileinput1.click()"
                      class="btn btn-block btn-all"
                      style="color: #f2f2f2"
                    >
                      {{ filename }}
                      <span v-show="!(form.files && form.files.length)" class="caret"></span>
                    </b-button>
                    <input
                      type="file"
                      @change="onSelectFile"
                      ref="fileinput1"
                      class="m--1"
                      style="display: none"
                      multiple="multiple"
                      required
                    >
                  </b-col>
                  <b-col sm="6" style="margin-bottom: 30px">
                    <button
                      class="shape-button btn"
                      ref="shapebtn"
                      @mouseover="stayShapeInput = true"
                      @mouseout="stayShapeInput = false"
                      v-show="(form.files && form.files.length) || showShape"
                    >
                      {{ !stayShapeInput ? "Shape:" : "Shape:" }}
                      <input
                        class="hidden-input"
                        ref="shape_input"
                        v-model="shape"
                      >
                    </button>
                  </b-col>
                </b-row>
                <b-alert
                  :show="dismissCountDown"
                  dismissible
                  variant="danger"
                  fade
                  @dismissed="dismissCountDown==0"
                  @dismiss-count-down="countDownChanged"
                  style="margin-bottom: 30px"
                >{{ error_msg }}</b-alert>
              </b-col>
              <div class="clearfix"></div>
              <b-col sm="6">
                <b-card v-if="form.files && form.files.length == 1" class="round-card">
                  <template>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>File Name:</b>
                      </b-col>
                      <b-col
                        sm="6"
                        class="text-right"
                        style="  text-overflow: ellipsis;overflow: hidden;white-space: nowrap;"
                      >{{ form.files[0].name }}</b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>File Size:</b>
                      </b-col>
                      <b-col sm="6" class="text-right">{{ form.files[0].size }} bytes</b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>File Type:</b>
                      </b-col>
                      <b-col sm="6" class="text-right">{{ form.files[0].type }}</b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>Last Modified:</b>
                      </b-col>
                      <b-col
                        sm="6"
                        class="text-right"
                      >{{ new Date(form.files[0].lastModified).toJSON().slice(0, 19).replace('T', ' ') }}</b-col>
                    </b-row>
                  </template>
                </b-card>
                <b-card v-if="form.files && form.files.length == 2" class="round-card">
                  <template>
                    <b-row class="mb-2" v-if="selectedType == 'float_model_data'">
                      <b-col sm="12" class>
                        <b v-if="float_model_data_converting">Estimating fixed model converting cost <i class="fa fa-spinner fa-spin" style="color: #5ac0db"></i></b>
                        <b v-if="!float_model_data_converting">Estimated converting cost:
                          <i>{{ ~~((form.files[0].size + form.files[1].size) / 10000) }}</i> CTXC
                        </b>
                      </b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>Parameters File</b>
                      </b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>File Size:</b>
                      </b-col>
                      <b-col sm="6" class="text-right">{{ form.files[0].size }} bytes</b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>Last Modified:</b>
                      </b-col>
                      <b-col
                        sm="6"
                        class="text-right"
                      >{{ new Date(form.files[0].lastModified).toJSON().slice(0, 19).replace('T', ' ') }}</b-col>
                    </b-row>
                    <b-row>
                      <br>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>Symbol File</b>
                      </b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>File Size:</b>
                      </b-col>
                      <b-col sm="6" class="text-right">{{ form.files[1].size }} bytes</b-col>
                    </b-row>
                    <b-row class="mb-2">
                      <b-col sm="6" class>
                        <b>Last Modified:</b>
                      </b-col>
                      <b-col
                        sm="6"
                        class="text-right"
                      >{{ new Date(form.files[1].lastModified).toJSON().slice(0, 19).replace('T', ' ') }}</b-col>
                    </b-row>
                  </template>
                </b-card>
              </b-col>
              <b-col sm="6">
                <b-card
                  v-if="form.files && form.files.length"
                  class="round-card description-card"
                  style="height: 144px"
                >
                  <p>
                    <b>Description</b>
                    <b-button
                      class="btn btn-sm pull-right btn-all"
                      @click="add_description=false"
                    >Save</b-button>
                  </p>
                  <b-form-textarea
                    ref="description_area"
                    v-model="form.description"
                    style="width: 100%; outline: none; box-shadow: none; color: #1a1a1a; background: none;"
                    rows="3"
                    no-resize
                  ></b-form-textarea>
                </b-card>
              </b-col>
              <div class="clearfix"></div>
              <b-col sm="6">
                <b-button
                  @click="onSubmit"
                  class="btn btn-all"
                  style="margin-right: 30px"
                  :disabled="!showShape || !(form.files && form.files.length)"
                >Upload</b-button>
                <b-button @click="onReset" class="btn btn-all btn-all-red">Cancel</b-button>
              </b-col>
            </b-row>
          </b-form-group>
        </b-form>

        <h2 style="margin-top:30px;" v-if="confirming.length > 0">Upload Data</h2>
        <div class="table-responsive">
          <b-table
            hover
            small
            :fields="fields_c"
            :items="confirming"
            class="transaction_table table-striped"
            v-if="confirming.length > 0"
          >
            <template slot="name" slot-scope="row">
              <span>{{ row.item.name }}</span>
            </template>
            <template slot="type" slot-scope="row">
              <span>{{ row.item.type }}</span>
            </template>
            <template slot="status" slot-scope="row">
              <span>{{ row.item.status }}</span>
            </template>
            <template slot="blockNumber" slot-scope="row">
              <a
                :href="`/block/${row.item.blockNumber}`"
                style="text-decoration: none"
              >{{ row.item.blockNumber}}</a>
            </template>
            <template slot="transactionHash" slot-scope="row">
              <a
                :href="`/tx/${row.item.transactionHash}`"
                style="text-decoration: none"
              >{{ row.item.showtransactionHash }}</a>
            </template>
          </b-table>
        </div>
        <h2 style="margin-top:30px;">Models</h2>
        <div class="table-responsive">
          <b-table
            hover
            small
            :fields="fields"
            :items="models"
            @row-clicked="toggleDetails"
            class="transaction_table table-striped"
            v-if="models.length > 0"
          >
            <template slot="blockNumber" slot-scope="row">
              <a
                :href="`/block/${row.item.blockNumber}`"
                style="text-decoration: none"
              >{{ row.item.blockNumber}}</a>
            </template>
            <template slot="contractAddress" slot-scope="row">
              <a
                :href="`/address/${row.item.contractAddress}`"
                style="text-decoration: none"
              >{{ row.item.contractAddress }}</a>
            </template>
            <template slot="shape" slot-scope="row">
              <span>{{ row.item.shape }}</span>
            </template>
            <template slot="hash" slot-scope="row">
              <b-button class="btn btn-all" @click.stop="setShapeFromContract(row.item)">Try It!</b-button>
            </template>
            <template slot="timestamp" slot-scope="row">
              <b-button style="background: transparent;padding: 0 12px">
                <i
                  class="fa fa-angle-down"
                  style="color: #5ac0db;font-weight: bolder;font-size: 20px"
                ></i>
              </b-button>
            </template>
            <template slot="row-details" slot-scope="row">
              <b-card class="bottom-round-card" ref="'item' + row.item.blockNumber">
                <b-button
                  style="border-radius:3px;width: 22px;position: absolute;top: 8px;right: 8px;z-index: 999"
                  size="xs"
                  @click="row.toggleDetails"
                >
                  <i class="fa fa-angle-up"></i>
                </b-button>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Block Number :</b>
                  </b-col>
                  <b-col class="col-xs-9">
                    <a :href="`/block/${row.item.blockNumber}`">{{ row.item.blockNumber }}</a>
                  </b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Author :</b>
                  </b-col>
                  <b-col class="col-xs-9">
                    <a href="`/address/${row.item.from}`">{{ row.item.from }}</a>
                  </b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Contract Address :</b>
                  </b-col>
                  <b-col class="col-xs-9">
                    <a href="`/address/${row.item.from}`">{{ row.item.contractAddress }}</a>
                  </b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Shape :</b>
                  </b-col>
                  <b-col class="col-xs-9">{{ row.item.shape }}</b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>File Size (bytes):</b>
                  </b-col>
                  <b-col class="col-xs-9">{{ row.item.size }}</b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Receive Time :</b>
                  </b-col>
                  <b-col class="col-xs-9">{{ new Date(row.item.timestamp*1000).toUTCString() }}</b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Info Hash :</b>
                  </b-col>
                  <b-col class="col-xs-9" style="color:green">{{ row.item.infoHash }}</b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>URI :</b>
                  </b-col>
                  <b-col class="col-xs-9">{{ row.item.uri }}</b-col>
                </b-row>
                <b-row class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Upload Progress:</b>
                  </b-col>
                  <b-col class="col-xs-9">
                    <b-progress :max="row.item.size" class="col-sm-3 col-xs-4">
                      <b-progress-bar :value="row.item.size - row.item.upload"></b-progress-bar>
                      {{ Math.max(row.item.size - row.item.upload, 0) }} / {{ row.item.size }}
                    </b-progress>&nbsp;&nbsp;
                    <span v-if="row.item.upload == 0" style="color:green">OK</span>
                    <span v-if="row.item.upload > 0">
                      <span style="color:red">Uploading</span>
                      , &nbsp; {{ Math.floor(row.item.upload / (10 * 512 * 1024)) + 1 }} Txs left to carry progress forward
                    </span>
                  </b-col>
                </b-row>
                <b-row v-for="(tx, index) in row.item.uploadTxs" :key="index" class="mb-10">
                  <b-col class="col-xs-3">
                    <b>Uploading Tx:</b>
                  </b-col>
                  <b-col class="col-xs-9">
                    Index Start: &nbsp;
                    <input v-model="tx.start" type="text">&nbsp;
                    Index End: &nbsp;
                    <input v-model="tx.end" type="text">&nbsp;
                    Endorphin Price: &nbsp;
                    <input
                      v-model="tx.gasPrice"
                      type="text"
                    >&nbsp;&nbsp;
                    <b-button
                      variant="danger"
                      @click="row.item.uploadTxs.splice(index, 1)"
                      size="xs"
                      class="delete"
                    >
                      <i class="fa fa-remove"></i>
                    </b-button>
                  </b-col>
                </b-row>
                <b-row style="margin-top: 20px" v-if="row.item.upload != 0">
                  <b-col class="col-xs-12 text-center">
                    <b-button
                      class="btn btn-all"
                      @click="add(row.item)"
                      :disabled="row.item.upload == 0"
                      style="margin-right: 30px"
                    >Add</b-button>
                    <b-button
                      class="btn btn-all btn-all-red"
                      @click="send(row.item)"
                      :disabled="row.item.upload == 0"
                    >Send</b-button>
                  </b-col>
                </b-row>
              </b-card>
            </template>
          </b-table>
          <h5 v-else class="transaction_table none">No record</h5>
        </div>
        <div class="pages" style v-on="utils">
          <span class="row">
            <a class="btn btn-sm btn-default" @click="jump_first()">
              <span class="glyphicon glyphicon-fast-backward"></span>
            </a>
            <a class="btn btn-sm btn-default" @click="jump_previous()">
              <span class="glyphicon glyphicon-step-backward"></span>
            </a>
            <a class="btn btn-sm btn-default">
              Page
              <input
                class="pages-input"
                :value="currentModelPage +1"
                size="4"
                id="jumpPage"
                @keyup.enter="jump_spec"
                type="text"
              >
              of &nbsp; {{ model_page_len }}
            </a>
            <a class="btn btn-sm btn-default" @click="jump_next()">
              <span class="glyphicon glyphicon-step-forward"></span>
            </a>
            <a class="btn btn-sm btn-default" @click="jump_last()">
              <span class="glyphicon glyphicon-fast-forward"></span>
            </a>
          </span>
        </div>
      </div>
      <div v-if="false && showWallet">
        <div style="position: fixed;top: 0;bottom: 0;left: 0;right: 0;background: rgba(0,0,0,0.4)"></div>
        <div class="wallet">
          <h2 style="margin-top: 10px;margin-bottom: 30px">Tips</h2>
          <h4 style="font-size: 16px">Please make sure you have
            <a href="https://github.com/CortexFoundation/Cortex_Release">installed</a> and logged in to our CortexWallet!
          </h4>
        </div>
      </div>
    </div>
    <div v-if="showModal" class="messageModal">
      <div
        style="position: fixed;top: 0;bottom: 0;left: 0;right: 0;background: rgba(0,0,0,0.4);z-index: 1000;"
      ></div>
      <div class="wallet" style="top: 30%;z-index: 1100;">
        <h2 style="margin-top: 10px;margin-bottom: 30px">Tips</h2>
        <h4 style="font-size: 16px">{{modalMessage}}</h4>
      </div>
    </div>
  </div>
</template>

<script>
import bus from "@/components/bus";
import { promisify } from "es6-promisify";
import CortexUtils from "../../../testutils/src/utils.js";
import Vue from "vue";
import { setTimeout } from 'timers';

export default {
  name: "DataUploadView",
  data() {
    return {
      float_model_data_converting: false,
      error_msg: "",
      showInfo: false,
      showWallet: false,
      showModal: false,
      modalMessage: "",
      canbeclose: false,
      add_description: false,
      dismissCountDown: 0,
      showShape: false,
      user: {
        name: "",
        key: null
      },
      utils: new CortexUtils(),
      form: {
        files: null,
        file: null,
        sender: null,
        recipient: null,
        description: ""
      },
      selectedType: "input_data",
      stayShapeInput: false,
      shape: "1,28,28",
      show: true,

      models: [],
      model_len: 0,
      model_page_len: 0,
      currentModelPage: 0,
      confirming: [],
      confirming_index: {},
      fields: [
        {
          label: "Block #",
          key: "blockNumber"
        },
        {
          label: "File Size (bytes)",
          key: "size"
        },
        {
          label: "Contract Address",
          key: "contractAddress"
        },
        {
          label: "Description",
          key: "description"
        },
        {
          label: "Shape",
          key: "shape"
        },
        {
          label: "Action",
          key: "hash"
        },
        {
          label: "Details",
          key: "timestamp"
        }
      ],
      fields_c: [
        {
          label: "File Name",
          key: "name"
        },
        {
          label: "Type",
          key: "type"
        },
        {
          label: "Stats",
          key: "status"
        },
        {
          label: "Block #",
          key: "blockNumber"
        },
        {
          label: "Tx Hash",
          key: "transactionHash"
        }
      ]
    };
  },
  methods: {
    countDownChanged(dismissCountDown) {
      this.dismissCountDown = dismissCountDown;
    },
    send_error(msg) {
      this.error_msg = msg;
      this.countDownChanged(5);
    },
    async toggleDetails(record, index) {
      let item = record;
      // if (!item._showDetails) {
      //   var latestBlock = (await this.utils.getBlockNumber()).toString(16);
      //   console.log(latestBlock);
      //   item.upload = await this.utils.upload_info(
      //     item.contractAddress,
      //     latestBlock
      //   );
      //   if (item.upload) item.upload = parseInt(item.upload);
      //   else item.upload = item.size;
      // }

      item._showDetails = !item._showDetails;
    },
    jump_spec($event) {
      this.utils.sync_record_model(this);
    },
    jump_first() {
      this.currentModelPage = 0;
      this.utils.sync_record_model(this);
    },
    jump_last() {
      this.currentModelPage = this.page_len - 1;
      this.utils.sync_record_model(this);
    },
    jump_previous() {
      if (this.currentModelPage > 0) this.currentModelPage--;
      this.utils.sync_record_model(this);
    },
    jump_next() {
      if (this.currentModelPage + 1 < this.page_len) this.currentModelPage++;
      this.utils.sync_record_model(this);
    },
    send(item) {
      for (let tx of item.uploadTxs) {
        for (var i = tx.start; i < tx.end; ++i) {
          this.utils
            .receiver(item.contractAddress)
            .upload_progress(tx.gasPrice);
        }
      }
    },
    async add(item) {
      var uploadTxs = item.uploadTxs;
      var gasPrice = Math.max(parseInt(await this.utils.gasPrice()), 18);
      uploadTxs.push({
        start: 0,
        end: Math.floor(item.upload / (512 * 1024)) + 1,
        gasPrice: gasPrice
      });
    },
    async setShapeFromContract(item) {
      if (!item.shape) {
        item.shape = await this.utils.getShapeFromContract(
          item.contractAddress
        );
      }
      const shape = item.shape;
      if (!shape) return;
      this.shape = shape.map(d => "" + d).join(",");
      this.showShape = true;
      if (this.$refs.shapebtn.className.includes("fade-in")) {
        this.$refs.shapebtn.className = this.$refs.shapebtn.className.replace(
          "fade-in",
          ""
        );
      }
      setTimeout(() => {
        if (!this.$refs.shapebtn.className.includes("fade-in")) {
          this.$refs.shapebtn.className =
            this.$refs.shapebtn.className + " fade-in";
        }
      }, 1000);
    },
    onSelectFile() {
      let files =
        this.$refs && this.$refs.fileinput1 && this.$refs.fileinput1.files;
      if (this.selectedType == "model_data") {
        if (files.length != 2) {
          this.form.files = null;
          this.send_error("Model data should be two files, params and symbol.");
        }
        if (files[0].name == "params" && files[1].name == "symbol") {
          this.form.files = [];
          this.form.files.push(files[0]);
          this.form.files.push(files[1]);
        } else if (files[1].name == "params" && files[0].name == "symbol") {
          this.form.files = [];
          this.form.files.push(files[1]);
          this.form.files.push(files[0]);
        } else {
          this.form.files = null;
          this.send_error("Model data should be two files, params and symbol.");
        }
      } else if (this.selectedType == "float_model_data") {
        this.float_model_data_converting = true;
        setTimeout(() => {
          this.float_model_data_converting = false;
        }, 6000);
        if (files.length != 2) {
          this.form.files = null;
          this.send_error("Model data should be two files, params and symbol.");
        }
        if (files[0].name == "params" && files[1].name == "symbol") {
          this.form.files = [];
          this.form.files.push(files[0]);
          this.form.files.push(files[1]);
        } else if (files[1].name == "params" && files[0].name == "symbol") {
          this.form.files = [];
          this.form.files.push(files[1]);
          this.form.files.push(files[0]);
        } else {
          this.form.files = null;
          this.send_error("Model data should be two files, params and symbol.");
        }
      } else if (this.selectedType == "input_data") {
        if (files.length == 1) {
          if (files[0].type == "" || files[0].type.includes("image")) {
            this.form.files = [];
            this.form.files.push(files[0]);
          } else {
            this.form.files = null;
            this.send_error("Input data should be an image file.");
          }
        } else {
          this.form.files = null;
          this.send_error("Input data should be one file.");
        }
      }
    },
    async onSubmit() {
      this.showModal = true;
      this.modalMessage = "Uploading...";

      this.utils.input_shape(this.shape.split(",").map(d => +d));
      this.utils.author(this.utils.web3.eth.defaultAccount);
      let torrent, payload, size, updateTagRes, price;
      let input_data_n = 0;
      let model_data_n = 0;
      let err_message = [];

      if (this.selectedType == "input_data") {
        let tem = {
          name: this.form.files[0].name,
          type: "Input Data",
          status: "Uploading"
        };

        this.confirming.push(tem);
        this.confirming_index[tem.name] = this.confirming.length - 1;

        torrent = await this.utils.encode_upload(this.form.files[0],
          this.form.description);

        if (torrent[1].data.msg == "ok") {
          this.showModal = true;
          this.modalMessage = "Upload Data Success.";
        }
        else {
          input_data_n = 1;
          this.showModal = true;
          this.modalMessage = "Upload Data failed.";
          err_message.push("Upload Data failed.");
        }

        updateTagRes = await this.utils.updateTag(
          torrent[0].infohash,
          this.form.description
        );

        if (updateTagRes.data.status == "success") {
          this.showModal = true;
          this.modalMessage = "Update Torrent Success.";
        }
        else {
          input_data_n = 2;
          this.showModal = true;
          this.modalMessage = updateTagRes.data.message;
          err_message.push(updateTagRes.data.message);
        }

        payload = await this.utils.create_input(torrent[0]);
        size = torrent[0].info.length;
        this.confirming[this.confirming_index[tem.name]].status = "Uploaded";
        console.log(torrent[0]);
      }
      else {
        let tem = {
          name: this.form.files[0].name,
          type: "Model Data",
          status: "Uploading"
        };
        this.confirming.push(tem);
        this.confirming_index[tem.name] = this.confirming.length - 1;
        torrent = await this.utils.create_torrent(
          [this.form.files[0], this.form.files[1]],
          this.form.description
        );
        updateTagRes = await this.utils.updateTag(
          torrent.infohash,
          this.form.description
        );

        if (updateTagRes.data.status == "success") {
          this.showModal = true;
          this.modalMessage = "Update Torrent Success.";
        }
        else {
          model_data_n = 1;
          this.showModal = true;
          this.modalMessage = updateTagRes.data.message;
          err_message.push(updateTagRes.data.message);
        }

        const response = await this.utils.upload_model(
          [this.form.files[0], this.form.files[1]],
          torrent.torrent,
          torrent.infohash
        );
        payload = await this.utils.create_model(torrent);

        size = torrent.info.files
          .map(file => file.length)
          .reduce((a, b) => a + b);

        if (this.selectedType == 'float_model_data') {
            price = "" + (~~(size / 10000)) + "000000000000000000";
        }
      }
      let name = this.form.files[0].name;
      if (
        (model_data_n == 0 || model_data_n == 1) &&
        (input_data_n == 0 || input_data_n == 2)
      ) {
        this.showModal = true;
        this.modalMessage = "Please Send Transaction.";

        setTimeout(() => {
          this.showModal = false;
        }, 2000);

        let name = this.form.files[0].name;
        this.confirming[this.confirming_index[name]].status = "Confirming";
        const receipt = await this.utils.push_data(payload, price);

        const c_name = this.confirming_index[name]
        this.confirming[c_name].status = "Confirmed";
        this.confirming[c_name].blockHash = receipt.blockHash;
        this.confirming[c_name].blockNumber = receipt.blockNumber;
        this.confirming[c_name].transactionHash = receipt.transactionHash;
        this.confirming[c_name].showtransactionHash =
          receipt.transactionHash.substring(0, 40) + "..";
        setTimeout(() => {
          this.showModal = false;
        }, 1000);
      }
      else {
        this.modalMessage = err_message;
        this.confirming[this.confirming_index[name]].status = "Upload failed";
        this.canbeclose = true;
        setTimeout(() => {
          this.showModal = false;
        }, 2000);
      }
    },
    onReset(evt) {
      evt.preventDefault();
      this.form.sender = "";
      this.form.recipient = null;
      this.form.files = [];
      this.show = false;
      this.$nextTick(() => {
        this.show = true;
      });
    },
    onUploadButtonClick: function(e) {
      var target = e.currentTarget;
      target = target.nextSibling.nextSibling.childNodes[0];
      target.click();
    }
  },
  async mounted() {
    $(".loading").css("display", "block");

    this.models = [];
    this.utils.sync_record_model(this);

    await this.utils.init(this);
    this.sender = this.utils.web3.eth.defaultAccount;

    $(".loading").fadeOut(500);
  },
  watch: {
    selectedType(newval) {
      this.form.files = null;
    },
    shape(newval) {
      this.showShape = true;
    }
  },
  computed: {
    filename() {
      if (!this.form.files || this.form.files.length == 0) {
        return "Select File";
      } else if (this.form.files.length == 1) {
        return this.form.files[0].name;
      } else {
        let name = "";
        for (let i = 0; i < this.form.files.length - 1; ++i) {
          name += this.form.files[i].name + ", ";
        }
        name += this.form.files[this.form.files.length - 1].name;
        return name;
      }
    },
    colClass() {
      const isType = ['model_data', 'float_model_data'].includes(this.selectedType)
      return isType ? "col-sm-6": "col-sm-12";
    },
    title() {
      return "Upload";
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.transaction_table_item {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
  max-width: 300px;
  text-decoration: none;
  cursor: pointer;
}

.transaction_table.none {
  text-align: center;
  padding: 2em;
  color: #a0a0a0;
}
.round-card {
  padding: 15px;
  margin-bottom: 30px;
  border: 1px solid #8f8f8f;
  border-radius: 3px;
  line-height: 2em;
}
.bottom-round-card {
  position: relative;
  margin: -8px;
  padding: 16px 8px;
}
.card-supplement {
  margin-top: 3em;
  margin-bottom: 3em;
}
.round-file-input,
.custom-file-input {
  padding: 10px;
  border-radius: 3px;
  border: 0;
}
.b-table-details {
  background-color: #f00;
}
tr.b-table-details:hover {
  background-color: inherit !important;
}
tr.b-table-details > td {
  padding: 0 !important;
}
.shape-button {
  background-color: #6c757d;
  color: white;
  min-width: 7em;
  border-radius: 3px;
  cursor: pointer;
}
.title-header {
  background-color: #112235;
  color: #fff;
}
.page-head {
  padding-top: 20px;
  min-height: 200px;
}
.btn {
  border-radius: 3px;
  outline: none !important;
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
.hidden-input {
  width: 6em;
  height: 20px;
  border: 1px dashed #fff;
  outline: none;
  background-color: transparent;
}
.table-responsive {
  min-height: 0.01%;
  overflow-x: auto;
}
.delete {
  width: 20px;
  color: #fff;
  border: none;
  border-radius: 50%;
}
.mb-10 {
  margin-bottom: 10px;
}
.table-hover > tbody > tr:hover {
  background-color: #777 !important;
}
.fa-question-circle-o {
  font-size: 20px;
  vertical-align: top;
  cursor: pointer;
  color: #aaa;
}
.info {
  position: absolute;
  padding: 15px;
  margin: 0;
  z-index: 20;
  left: 0;
  right: 0;
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 3px;
  margin: 0px;
}
.progress {
  padding: 0;
  margin-bottom: 0;
  text-align: center;
  border: 1px solid #ddd;
  box-shadow: none;
}
.progress-bar {
  background: #1a9cb5;
}
.wallet {
  position: absolute;
  max-width: 375px;
  width: 100%;
  top: 100px;
  left: 50%;
  margin-left: -187px;
  padding: 15px;
  color: #000;
  background: #fff;
  border-radius: 4px;
}
.messageModal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1050;
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
  outline: 0;
}
.btn-upload {
    position: relative;
    display: block;
}
.upload-info {
    display: none;
    position: absolute;
    border: 1px solid #000;
    bottom: 30px;
    left: 50px;
    right: 0;
    background: #fff;
    z-index: 2;
    padding: 15px;
}
.btn-upload:hover .upload-info {
    display: block;
}
</style>
